# APM466 Assignment 3: Credit Risk

In [ ]:
import math
import numpy as np
from scipy import linalg

## Question 1

### Part (a)

In [ ]:
P = np.matrix([[7/10, 2/10, 1/10, 0],
              [1/10, 5/10, 2/10, 2/10],
              [1/10, 3/10, 3/10, 3/10],
              [0, 0, 0, 1]])

np.linalg.matrix_power(P, 3)

matrix([[0.405, 0.281, 0.148, 0.166],
        [0.148, 0.244, 0.131, 0.477],
        [0.133, 0.204, 0.113, 0.55 ],
        [0.   , 0.   , 0.   , 1.   ]])

### Part (b)

In [ ]:
##### implementation of function for finding the matrix fractional powers #####
# this returns similar results as scipy.linalg.fractional_matrix_power

def frac_comb(n, r):
    '''
    Calculates combinations function (nCr) with fractional numbers,
    noting that scipy.special.comb only works for integers
    '''
    k = 0
    prod = 1
    while k < r:
        prod *= (n-k)
        k +=1

    return prod/math.factorial(r)


def frac_pow(M, p, ep):
    '''
    Finds fractional power of a matrix with iterative approach until convergence
        M - input matrix
        p - fractional power
        ep - convergence threshold
    '''
    k = 0
    sum = np.zeros((4,4))
    prev = np.matrix.copy(sum)
    diff = 999
    
    while diff > ep:
        sum += frac_comb(p, k) * np.linalg.matrix_power(M-np.identity(4), k)
        diff = np.linalg.norm(sum-prev)
        prev = np.matrix.copy(sum)
        k += 1

    return sum

In [ ]:
linalg.fractional_matrix_power(P, 1/6)

array([[ 0.93805429,  0.04759609,  0.0221279 , -0.00777827],
       [ 0.0221279 ,  0.86373589,  0.08099898,  0.03313723],
       [ 0.02546819,  0.11982833,  0.7827369 ,  0.07196658],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

### Part (c)

In [ ]:
np.linalg.matrix_power(P, 10000)

matrix([[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]])